src/windows/room/chat.rs

Fix file never downloading (unless it has been downloaded in the past and using `!` force flag).
The logic should be:
* If file does not exist, or `!` force flag used, then download it
* Else if neither `!` or `:open` flag used, then error out
and then return downloaded-message or open-and-message.
I.e. `:open` should still open the file if it has already been downloaded. Otherwise the only way to open it is to use `!` and re-download it.

fix: attachment download flags + exists check

---

README.md
flake.lock
flake.nix

Since it's a flake, it should rely on Cargo.lock and not require maintenance, except when a new system dependency is added, which is rare with cargo. Currently the only ones are openssl and pkg-config.

Add Nix flake

---

src/config.rs

The current error message is
thread 'main' panicked at 'no dirs.download value configured!', src/config.rs:327:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
which is not only unelegant, but also wrong. The key iamb expects is `dirs.downloads`, which is now also reflected in the error message.

Fix error message for undefined download directory

---

Cargo.lock
Cargo.toml
src/base.rs
src/windows/room/chat.rs

`:upload` argument is made optional. If omitted, then it will try to grab an image from the clipboard instead.
The user might not know this behaviour and the command does not indicate that the clipboard will be grabbed and uploaded without any confirmation. There could be sensitive information in it.
There should be some mechanism to confirm/ask the user, or await a "manual paste" (Ctrl-V? Shift-Ctrl-V?). I don't really know how to go on about "command steps" or something like that. @ulyssa wdyt?

Support uploading image attachments from clipboard

---

.github/workflows/ci.yml
src/windows/room/chat.rs

GitHub is deprecated node.js v12 runners and the `set-output` command, both of which are currently used within the `ci.yml` action. They were initially slated to stop working at the [end of this month](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), but it looks like that's been pushed back to some TBD date.
Since they're unmaintained, and don't seem likely at this point to be updated by the time that GitHub turns off the deprecated functionality, I'm going to replace [`actions-rs/toolchain`](https://github.com/actions-rs/toolchain/) with [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and [`actions-rs/clippy-check`](https://github.com/actions-rs/clippy-check) with …

Replace GitHub actions using deprecated features

---

src/config.rs
src/tests.rs
src/windows/room/chat.rs

Allow setting "open_command" to array of [program, args...] as alternative to using `open::that`.
The `open-rs` crate now has [`open::with_command`](https://docs.rs/open/4.1.0/open/fn.with_command.html), but that only allows adding args _after_ the path arg. In my case I need `firefox --new-window path` and that seems like the most common case.
@ulyssa the two fns in chat.rs feel a bit randomly placed, but I didn't want to decide on anything about files/modules in this PR. Feel free to suggest some better organization.

Support configuring which program `:open` runs

---

.gitignore
flake.nix

Hi there,
building iamb on darwin requires the `AppKit` and `Security` frameworks which must be explicitly specified as dependencies when using nix.
Additionally I've removed `openssl` from the `nativeBuildInputs` as it's only required in `buildInputs` and added the `result` output directory used by nix to the gitignore file.

Fix Nix flake build on Darwin

---

docs/example_config.json

- docs: add missing brace to example config
- docs: fix paths in example config

fix example config

---

Cargo.lock
Cargo.toml
src/base.rs
src/commands.rs
src/main.rs
src/windows/room/chat.rs

I found it not that difficult to implement this feature that I wanted.
If there are some issues with the current implementation, I would be glad to fix them.
PR adds a new command `:editor` that opens `$EDITOR` in the current window or in a new one (if `$EDITOR` is a GUI one),  using a new temporary file, the message from this file will be sent immediately after leaving the editor.
Also, current text from a buffer (if any) will be used as the initial content of the file.

Support composing messages in an external editor

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
README.md

The CI workflow broke when I updated the `Cargo.lock`, since it started pulling in packages that can't build with 1.66. I'm adjusting the dependencies again so that things will work with the new MSRV, 1.67.

Fix CI workflow

---

src/base.rs
src/message/mod.rs
src/tests.rs
src/worker.rs

On my machine, this reduces idle CPU usage from 150% to ~0.5%.

Reduce CPU usage by instead fetching read receipts after related sync events

---

README.md
src/base.rs
src/config.rs
src/tests.rs
src/windows/mod.rs
src/windows/room/space.rs
src/worker.rs

This adds a new `"sort"` field to the `"settings"` object that allows configuring how the lists of rooms and users in `:rooms`, `:dms`, `:spaces`, `:members` are sorted.

Support custom sorting for room and user lists

---

Cargo.lock
Cargo.toml
README.md
src/main.rs
src/worker.rs

Use `matrix-sdk`'s `sso-login` feature to provide SSO login.
Gives an interactive option at launch time for users to pick between SSO and password authentication.
In common with [the `matrix-sdk` project](https://github.com/matrix-org/matrix-rust-sdk/pull/176#issuecomment-800318936), I couldn't figure out any way to test this feature because it relies on a browser. If there's anything that I should do, please say! :)
First PR in Rust, so please feel free to criticize!!

Add support for logging in with SSO

---

iamb.desktop

Howdie!
I'm not sure if this is something you'd like to keep, but I put together a desktop file per https://specifications.freedesktop.org/desktop-entry-spec/latest/
I've manually tested this by copying it into ~/.local/share/applications/ and then restarting my desktop environment (GNOME in this case)
There's no custom Icon=... field defined here, but otherwise it works quite well (for me, at least)

Add desktop file for GUI environment launchers

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
README.md
docs/example_config.json
docs/iamb.5.md
flake.nix
src/base.rs
src/config.rs
src/main.rs
src/message/mod.rs
src/preview.rs
src/tests.rs
src/windows/room/scrollback.rs
src/worker.rs

An image says more than a thousand words:
There has been some work to get some small change into ratatui that allows for "skipping" of rendering some cells (characters). This in turn allowed to make a crate [ratatui-image](https://github.com/benjajaja/ratatui-image) that provides a image widgets for ratatui, taking care of the terminal's graphics protocol automatically. Currently the supported "protocols" are sixels, kitty, and unicode-halfblocks. iTerm2's protocol should be easy to add, I just don't have access to a mac.
This PR uses ratatui-image widget's `render()` method to render images in the `ScrollBack` widget, in the chat lines. This seems hacky, but this kind of usage was actually intended and recommended for these kind of use cases in the discussion on the ratatui PR. …

Add support for previewing images in room scrollback

---

src/message/mod.rs

There was a hardcoded offset of `1` for the borders. With @ulyssa's fix for vertical splits, that can be removed now, as it displaces all previews one character too much to the right.
There some other offset bugs related to the layout-by-width in `get_render_format` not being replicated by `line_preview`, which should probably by unified some way.

Fix image preview offset

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml

Luckily, someone has written a native rust sixel library in the meantime! With **just** the API we need here.
Should get rid of libsixel (and its dependencies) linker errors.
Fixes #180

Update to ratatui-image@0.4.3 to use native sixel lib

---

.envrc
.gitignore

Allot of nix users use [direnv](https://direnv.net) for automatically entering the devshell.
Here is an example on how it looks on a direnv enabled nix machine:
https://github.com/ulyssa/iamb/assets/19208988/be4dc63a-3b87-46b6-9c2d-3c3936d5b8e0
With this change, nix users do not even have to think about devshells. It enters and exits the devshell automatically.
This will make contributing even easier :)

Enable direnv for Nix flakes

---

src/base.rs
src/windows/mod.rs
src/windows/room/mod.rs
src/windows/room/scrollback.rs
src/worker.rs

Fixes #149
The display_names only got populated from the
OriginalSyncRoomMemberEvent. When opening an already synced room, display_names is not populated.
ClientWorker::get_room extends the returned FetchedRoom to include RoomMembers from Room::members_no_sync. This allows RoomState::new to populate the RoomInfo's display_names.
Thanks to @Benjamin-L for finding the source of the bug in that issue. It was mentioned that it might be problematic to iterate over all members of large rooms. The largest room I had available to test this was only about 200 members, but it seemed fine.

Fix not showing display names in already synced rooms

---

src/message/mod.rs

The "placeholder frame" was not checking bounds and substracting.
Fixes #196

Fix crash on small image preview

---

src/base.rs
src/commands.rs
src/config.rs
src/message/mod.rs
src/windows/mod.rs
src/windows/welcome.md
src/worker.rs

Hello everyone,
It's my first PR in rust so feel free to criticise.
The PR adds `:chats` command, listing both DMs and Rooms. I've added a tag [DM] or [ROOM] to make sure we can differenciate if two have the same name.
(related to #172 )

Add a new `:chats` window that lists both DMs and Rooms

---

src/message/mod.rs
src/util.rs

Found out about this one when somebody with the displayname "qxofficial🍥🏳️‍⚧️" joined the rust room. This string is 30 bytes long in utf8, so iamb decided to truncate it at byte 28. This happens to be in the middle of the VS16 codepoint, which caused a panic.
`take_width` calculates the width of a grapheme cluster by adding the width of all it's code points under UAX#11. This overcounts many emoji sequences, like 🏳️‍⚧️, which consists of "🏳<ZWJ>⚧". Calculating the width of a name wrong currently causes the entire messages window UI to be misaligned, which is why this PR is marked as a draft.
The tricky bit is that the number of terminal cells that 🏳️‍⚧️ takes up varies depending on your font and terminal emulator. In some contexts, it will display as 🏳️‍⚧️ (one cell), while in others it …

Fix truncation/padding for non-ASCII sender names

---

Cargo.lock
Cargo.toml
src/base.rs
src/commands.rs
src/config.rs
src/keybindings.rs
src/main.rs
src/message/html.rs
src/message/mod.rs
src/message/printer.rs
src/preview.rs
src/tests.rs
src/util.rs
src/windows/mod.rs
src/windows/room/chat.rs
src/windows/room/mod.rs
src/windows/room/scrollback.rs
src/windows/room/space.rs
src/windows/welcome.rs

I split the `modalkit` dependency up into several crates, and moved some things around to hopefully make it easier for people to understand how things piece together. This PR reorganizes the impacted imports, and also takes care of updating for the `EditContext` trait to struct change.

Update modalkit dependencies

---

src/base.rs
src/config.rs
src/main.rs
src/tests.rs
src/windows/mod.rs
src/windows/room/scrollback.rs
src/worker.rs

This fixes #83 by adding two new fields to sort on, `unread` and `recent`. I've updated the sort order for `"rooms"` (and therefore by default all of the other room-like lists) to now be `["favorite", "lowpriority", "unread", "name"]`, so that favorites will still be at the top, and low-priority items at the bottom of the list, with unreads at the top inside those groups, and finally sorted by names.
The `"recent"` sort field can be used by folks who also want rooms to move within the list based on how recently someone has messaged there. This could potentially be annoying for users in multiple rooms with frequent activity that keep swapping positions in the list, so  I haven't put it in the default sort.

Indicate and sort on rooms with unread messages

---

Cargo.toml

The AUR `iamb-git` package seems to be broken right now due to some kind of weirdness with the LTO. A user reported in `#iamb-users:0x.badd.cafe` that they get the following:
```
/usr/bin/ld: /home/rek2/.cache/paru/clone/iamb-git/src/iamb/target/release/deps/iamb-dee5b80dcda0a0a7: hidden symbol `GFp_ia32cap_P' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
= note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
= note: use the `-l` flag to specify native libraries to link
= note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname) …
```

Move LTO into its own "release-lto" profile

---

README.md
src/config.rs
src/tests.rs
src/worker.rs

This fixes #158, and should help people avoid accidentally using the wrong homeserver during setup when the `/.well-known/matrix/client` points at a different domain.

Support following the .well-known entries for a username's domain

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
README.md
src/base.rs
src/config.rs
src/main.rs
src/message/mod.rs
src/sled_export.rs
src/tests.rs
src/windows/room/chat.rs
src/windows/room/mod.rs
src/worker.rs

This is a WIP update to use a newer version of the matrix-sdk. Several notes:
- I still need a solution for migrating keys from the sled store into sqlite, so this only works on new logins
- This required bumping the MSRV to 1.70, so anyone still using 1.67 will need to update
- The sqlite store is now stored under `$XDG_DATA_HOME/iamb/profiles/$PROFILE/sqlite` instead of under `$XDG_CONFIG_HOME/iamb/profiles/$PROFILE/matrix` like the sled store was, as discussed in `#iamb-users:0x.badd.cafe` a couple months back

Update to matrix-sdk@0.7.1

---

src/worker.rs

From what I can tell, it looks like the SDK defaults to `BackupDownloadStrategy::Manual`. I think that `BackupDownloadStrategy::AfterDecryptionFailure` is probably what most users expect, so I'm going to switch to that, and to creating backups by default when one doesn't already exist.

Download rooms keys from backups if they exist

---

src/base.rs
src/message/mod.rs
src/worker.rs

In #205 I added a `Need::MESSAGES` for every room at startup, which locks up the UI for the first several seconds when there are enough joined rooms. This adds an upper limit on how many load plans we execute in parallel at a time, and moves the receipt loading for a room to be outside of the `load_insert` function. This reduces the demand on the lock enough that the UI remains responsive.

Load receipts for room before acquiring lock

---

flake.nix

This is probably related to #204 
I tried to install the package from the flake but I had an error regarding the hash of modalkit. When I removed it from flake.nix It complained about the hash of keybindings, so I generated a new hash and added it to the flake.nix and it was smooth sailing from there.

Fix Nix flake hashes

---

flake.lock
flake.nix

- Updates the cargo hashes again
- Updated Rust  because matrix-sdk-common 0.7 was refusing to build on 1.67
- Used the current git commit hash as the version (appends -dirty if working tree is dirty)
- Small cleanups here and there

Nix flake updates

---

src/base.rs
src/main.rs
src/message/mod.rs
src/tests.rs
src/windows/mod.rs
src/windows/room/chat.rs
src/windows/room/mod.rs
src/windows/room/scrollback.rs
src/windows/room/space.rs
src/worker.rs

This adds initial support for entering messages threads. A thread can be entered by pressing `<Enter>` on the thread  root message. Messages entered into the message bar are then sent to the thread. You can navigate back to the main view using `^O`, just as with navigating back to other previous views.
I'm planning to add a `:threads` command to show the threads in the room, but this will require implementing loading non-continous ranges of messages in order to work well.

Add support for threads

---

Cargo.lock
Cargo.toml
docs/example_config.json
flake.nix
src/config.rs
src/keybindings.rs
src/main.rs
src/tests.rs

This adds a `"macros"` field to `config.json` which allows specifying custom mappings from one set of keys to another. This allows writing something like the following to map `jj` to `<Esc>` in Insert mode:
```json
{
...,
"macros": {
"i": { "jj": "<Esc>" }
}
}
```
The following names can be used to refer to the different modes:
- `normal`/`n` for Normal mode
- `insert`/`i` for Insert mode
- `visual`/`v` for Visual mode
- `command`/`c` for Command mode
- `select` for Select mode
-  `operator-pending` for Operator Pending mode
Multiple modes can be specified together using `|` to put a mapping in all of them. For example, `"insert|command"` or `"i|c"` could be used in the above example to map `jj` in both Insert and Command mode.
I've called this `"macros"` since they'll behave like macros: …

Add support for custom key macros

---

Cargo.toml
PACKAGING.md

This fixes #84 by adding a way to build that links against the system `libssl`/`libcrypto` libraries. I've also made it possible to link against the system SQLite, and added a `PACKAGING.md` that package maintainers can reference for useful building tips.

Support linking against system OpenSSL

---

.github/workflows/ci.yml
Cargo.lock

#218 broke the `Cargo.lock`. In addition to fixing it, the CI workflow should use `--locked` to make sure the PR has an updated `Cargo.lock` whenever the `Cargo.toml` is changed.

GitHub workflow should use `--locked` to avoid broken Cargo.lock

---

src/main.rs

Keys currently get typed twice on platforms where `crossterm` can detect key releases (like Windows) . I imagine that this would also apply if I ever turned on the kitty keyboard protocol for terminals that support it. When iamb sees a key release, it should just skip it.

Ignore key releases on platforms that support it

---

src/worker.rs

The CI failed for Windows in #192 due to not being able to infer the type parameter for an `.as_ref()` call. I can reproduce it with that PR checked out on Windows, but not on other platforms (or without that PR checked out). I'm not sure what the issue is, but it's easy enough to fix so that the the PR can compile in CI.

Fix odd Windows-only compile error

---

Cargo.lock
Cargo.toml
docs/iamb.5.md
src/base.rs
src/config.rs
src/main.rs
src/notifications.rs
src/tests.rs
src/windows/room/scrollback.rs
src/worker.rs

Basic notifications feature.
Can be enabled in config.json, disabled by default.

Add support for desktop notifications

---

docs/example_config.json
docs/iamb.5.md
src/config.rs
src/message/html.rs
src/message/mod.rs
src/message/printer.rs
src/tests.rs
src/util.rs

The font in my terminal doesn't support most emoji characters and shows ugly placeholders instead. For reactions, there is the setting `reaction_shortcode_display` that allows me to see human-readable shortcodes instead of the emojis. However, for emojis in messages there is no such feature.
I added a new setting `message_shortcode_display` that controls whether shortcodes are displayed instead of emojis in messages.
Replacing emojis with shortcodes happens in `TextPrinter` (or, for plain text, in `Message::show_msg()`).
I hope the changes are alright. I'd be happy to improve the code further and I'd be grateful for some feedback as I'm not very experienced in Rust yet.

Support displaying shortcodes instead of emojis in messages

---

docs/iamb.5.md
src/config.rs
src/message/mod.rs
src/tests.rs
src/windows/room/scrollback.rs

I found the user gutter too wide by default, especially when using localpart or display name for usernames so i made it configurable. Seems to work fine but I'm not a rustacean so there is perhaps a more idiomatic way to do this.

Support configuring user gutter width

---

src/base.rs
src/message/mod.rs
src/tests.rs
src/windows/room/chat.rs
src/windows/room/scrollback.rs
src/worker.rs

#152 defaulted to showing the non-thread messages when trying to enter a brand-new thread, which is confusing. The `ScrollbackState::get_thread` method should return an `Option` when there's nothing to view.
I've also refactored `Message::show` to make it easier to follow now that it's also got the thread count logic.

Fix entering thread view when there's no messages yet

---

src/message/mod.rs
src/windows/room/scrollback.rs

If an image preview is in a reply to a multiline message then the offset it's displayed at is wrong. This moves the logic for calculating it into `show_with_preview` where it can be done together with calculating the image text.

Fix image previews in replies

---

src/message/mod.rs

It would be nice to have `http[s]://` links automatically linked without always having to do the `<https://...>` syntax.

Enable autolinking when rendering Markdown

---

docs/iamb.5.md
src/base.rs
src/config.rs
src/main.rs
src/notifications.rs
src/tests.rs

This adds a `via` field to the `notifications` object that allows configuring whether to send notifications using the desktop mechanism (`"desktop"`, the default), or the terminal bell (`"bell"`).

Support notifications via terminal bell

---

src/windows/room/chat.rs

Adding a `!` to `:cancel` should do the same behaviour as running `:cancel` and typing `y` just like `!` does with other commands.

Reset message bar when `!` is passed with :cancel

---

docs/iamb.1
src/base.rs
src/commands.rs
src/main.rs

This adds `:keys import` and `:keys export` commands for importing and exporting room keys.

Add commands for importing and exporting room keys

---

src/main.rs
src/worker.rs

There seems to be a race where sometimes the client crashes on the `client.notification_settings().await` call because the client isn't logged in yet. All of the background refresh/notification tasks can just until the client is successfully logged in before doing anything.

Wait to log in before starting background tasks

---

src/base.rs
src/windows/room/chat.rs

[![asciicast](https://asciinema.org/a/TNtENBq6HgH4VZomwNfvD82S2.svg)](https://asciinema.org/a/TNtENBq6HgH4VZomwNfvD82S2)

Prevent sending duplicate reaction events

---

src/config.rs
src/message/mod.rs

This fixes #243 by adding a method to get the user color override or the default when there isn't one from `ApplicationSettings`.

Use color overrides for users when `message_user_color` is enabled

---

config.example.toml
docs/iamb.5
src/config.rs
src/tests.rs
src/windows/room/chat.rs

When using the `editor` command in iamb, the temporary file currently has no file extension. This is probably a reasonable default behavior, but some users may want to hint to their editor a particular file type such as `.md` or `.txt` to make use of linters, formatters, spell checkers, or other file type specific editor configurations.
This PR ~~preserves the default behavior~~ sets the default suffix to `.md` while adding a `external_edit_file_suffix` configuration option which accepts a string to append to the end of the temporary file name passed to the users editor.

Add `external_edit_file_suffix` to config

---

src/windows/welcome.md

This fixes #248 by updating the text in the `welcome.md` file to reference `config.toml` instead of `config.json`.

Update Welcome window to reference TOML instead of JSON

---

src/message/mod.rs

Currently image previews are printed one line too high if the message had a date inserted into it indicating a change of date between the current and preceding message. With this PR we conditionally check if a date was inserted and adjust the y offset used to place the rendered the image.
Tested in: `XTerm(374)`, `wezterm 20240203-110809-5046fc22`, and `konsole 24.02.1`.
Before change:
After change:

Fix image preview placement when messages are preceded by a date in the timeline

---

src/keybindings.rs
src/main.rs

This fixes #271 (and #255 in the right terminals) by enabling the Kitty keyboard enhancement protocol. In order to benefit from this, you'll need to be using a terminal that supports one of:
- The Kitty [keyboard enhancement protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/) :
- [alacritty](https://github.com/alacritty/alacritty/)
- [foot](https://codeberg.org/dnkl/foot)
- [kitty](https://sw.kovidgoyal.net/kitty/)
- [rio](https://github.com/raphamorim/rio/)
- [wezterm](https://wezfurlong.org/wezterm/)
- [Enabling the key sequence](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Functions-using-CSI-_-ordered-by-the-final-character-lparen-s-rparen:CSI-gt-Pp;Pv-m.1EB3) for the xterm-style [`modifyOtherKeys`](https://invisible-island.net/xterm/manpage/xterm.html#VT100-Wid …

Allow typing newline with `<S-Enter>` and enable keyboard enhancement protocol

---

Cargo.lock
Cargo.toml
src/message/mod.rs
src/util.rs
src/windows/mod.rs
src/windows/room/mod.rs
src/windows/room/space.rs

This updates the version of `modalkit` and `modalkit-ratatui` to pull in the following changes:
- ulyssa/modalkit#138
- ulyssa/modalkit#139
- ulyssa/modalkit#140

Update to modalkit{,-ratatui}@0.0.19

---

README.md

The package is now hosted in the main openSUSE Tumbleweed repositories. This corrects the README to use the openSUSE repo instead of a user-maintained one.

Fix openSUSE link and installation command in README

---

src/windows/room/chat.rs

Hi,
Quick fix for #246 by trimming the editor output and checking if it's empty.

Trim `:editor` output and check if it's empty

---

src/commands.rs

Adds error message if no argument is supplied.
Now `Failed command: Error: Missing username` is displayed if no username is given.
Did not remove username requirement for single account clients since different behavior depending on number of accounts could be confusing.
Fix for #268

Add error for missing username on `:logout`

---

Cargo.lock
Cargo.toml
src/message/mod.rs

Hi, first PR to take a look at the code base of this project (and a bit more at matrix internals).
It displays the attachment file size by appending it in the displayed messages.
For example, it would show `[Attached Image: Alt Text (12.34 kB)]` or `[Attached Image: Alt Text]` if the `size` field is not present in the message information.
Adds the `humansize` crate to `Cargo.toml`.
Intends to fix #97

Display file sizes for attachments

---

src/notifications.rs

this fixes #313 by removing the specified timeout

Remove timeout for desktop notifications

---

src/base.rs
src/config.rs
src/message/html.rs
src/message/mod.rs
src/windows/mod.rs
src/windows/room/scrollback.rs

I'd like to take this client to my own use but as long as it breaks "broken glass" invariant I really cannot do that ;-) [1]
Is there something broken in the CI, I see that there are some clippy bits but cannot comprehend why those checks are not working?
[1] "Fight software rot" chapter in "Pragmatic Programmer"

Fix newer Clippy warnings for 1.80

---

README.md

Hi,
The aim of it is to update iamb's documentation to include the Hombrew repository link and the command to install iamb on MacOS.
Also, I alphabetically sorted the install instructions for each platform.

Add Hombrew as install method on MacOS

---

src/base.rs
src/main.rs
src/notifications.rs

Hi,
This PR is to implement #276.
It does this by putting the `focused` state of the application into the store and then checks it in the notifications handler.
This results in notifications being muted only if the room is currently displayed and the terminal is in focus.
If you would like a config entry to control this just let me know. :)

Allow notifications on open room if terminal not focused

---

docs/iamb.1
src/base.rs
src/commands.rs
src/windows/room/mod.rs

This commit solves #50 by providing a way to:
- Set the canonical alias of a room (destroying the previous one if any)
- Unset the canonical alias of a room (destroying the previous one if any)
- Add an alternative alias to a room
- Delete an alternative alias to a room (destroying it afterwards)

Implement set/unset/show for alternative and canonical aliases

---

PACKAGING.md
docs/iamb.metainfo.xml

This is for flathub/flathub#5110, which should then allow resolving #295 .

Add FreeDesktop MetaInfo file

---

Cargo.lock
Cargo.toml
docs/iamb.1
src/message/compose.rs
src/message/mod.rs
src/notifications.rs
src/windows/room/mod.rs

This resolves #316 by adding commands that can be prefixed to messages. For now, I've only allowed using one at a time, but it may make sense in the future to allow combining `/me` with the other slash commands, instead of always interpreting its body as markdown.

Add message slash commands

---

src/base.rs
src/commands.rs
src/windows/room/chat.rs

Folks were talking about custom reactions and literal text reactions in the `#offtopic:archlinux.org` room earlier tonight. This PR changes `:react`/`:unreact` to prompt whether you want to use the literal text when it's not a shortcode, and allows using `:react!`/`:unreact!` to force it to be interpreted literally. (So `:react wave` sends the :wave: Emoji, and `:react! wave` reacts with the literal text "wave".)
I'd love to eventually support something like [MSC4027](https://github.com/matrix-org/matrix-spec-proposals/pull/4027), but that'll have to wait for some future PR.

Support reacting literally with non-Emojis

---

Cargo.toml
PACKAGING.md

For the upcoming release I'd like to provide `.deb` and `.rpm` files in addition to the tarballs on the release page, which should make it easier for folks to just `dpkg -i ...` and have the binary in their `PATH` and the manual pages in their `MANPATH`. This adds the metadata for using [cargo-deb](https://crates.io/crates/cargo-deb) and [cargo-generate-rpm](https://crates.io/crates/cargo-generate-rpm) to `Cargo.toml`.

Add metadata for `cargo-deb` and `cargo-generate-rpm`

---

src/message/printer.rs

This fixes #310, where the `TextPrinter::remaining` function can panic on underflow due to the width getting too large after a `push_span_break` method call.

Fix underflow panics when using `TextPrinter::push_span_nobreak`

---

.github/workflows/binaries.yml
.github/workflows/ci.yml

This moves the artifact uploading into its own action that runs on `main` and does cross-compilation to `aarch64` in addition to the `x86_64` binaries currently attached to the actions. I've built on top of #321 to also build `.deb` and `.rpm` files and upload those to the action, too.

Build cross-platform binaries and packages of main

---

src/main.rs

I somehow hallucinated support for xterm's `modifyOtherKeys` in `crossterm` when I did #272. If it ever does gain it, then I'll revert this. I don't know how I concluded that it supports them, but since it doesn't it breaks terminals like xterm or wezterm that do have support for them. (I suspect that I was initially using `\x1B[>4;1m` and then at some point switched to `\x1B[>4;2m` without retesting in those terminals.)

Remove modifyOtherKeys enablement

---

src/message/compose.rs

This is a first stab at improving the issue reported in #306 by not generating a `formatted_body` unless the text actually contains Markdown. I've done this for now based on characters used, which largely ends up meaning "doesn't contain ASCII punctuation" except for single and double quotes which are okay.
There's still some room for improvement in a future PR: Element will generate a `formatted_body` without surrounding `<p>` tags as long as everything fits on one line. While the `<p>` tags should be harmless, it seems like some clients will show them with trailing space in the timeline, which makes messages sent from iamb take up additional space. (This seems to be most egregious in Element Android. Element Web, Element iOS and FluffyChat don't seem to add any extra space that I notice …

Avoid treating simple messages as Markdown

---

Cargo.lock
Cargo.toml
src/config.rs
src/notifications.rs

This adds the room name to desktop notifications, and sends the `iamb` icon name so that folks with an icon installed under `/usr/share/icons/` will see it in the notification.
I've also created a new `desktop` default feature with the goal of making it possible to compile with or without pulling in `arboard` and `notify-rust` and all of the x11/wayland/dbus dependencies, which should make it easier to compile smaller `iamb` binaries that run on a remote machine and are used over SSH. This effort seems to be currently thwarted by `modalkit-ratatui`'s dependency on `modalkit` enabling the `default-features` set and pulling in `arboard`, so it will be imperfect until I do something about that.

Include room name in desktop notifications

---

docs/iamb.1
src/base.rs
src/commands.rs
src/windows/room/mod.rs

As mentioned in the issue #304, I couldn't find a way to set notification options.
Here is an attempt to implement it. It isn't working, I'm not sure why so help is appreciated.
I apologize for breaking formatting, maybe my editor isnt picking up the rustfmt.toml from the repo?
If we get this working we can fix that later

Add command to set per-room notification levels

---

docs/iamb.1
src/base.rs
src/commands.rs
src/windows/room/mod.rs

This adds commands for managing room memberships, each accepting an optional reason:
- `:room ban [user] [reason]`
- `:room unban [user] [reason]` 
- `:room unban [user] [reason]`

Add ban/unban/kick room commands

---

src/base.rs
src/commands.rs
src/windows/room/mod.rs

This fixes #91 by adding a `:room history set [level]` command with `unset` and `show` variants. The different visibility levels are:
- `invited`, which configures the room to allow people to see history from the point they were invited onwards.
- `joined`, which configures the room to allow people to see history from the point they actually join the room.
- `shared`, which configures the room to allow people to see all history once they are joined, including messages from before they joined.
- `world` which configures the room to allow anyone to see the room history regardless of whether they are joined and in it.

Add command for setting room history visibility

---

src/message/mod.rs

This fixes the issue with running the iamb tests on i686 seen in void-linux/void-packages#49652. I initially tried to do this in modalkit, but ended up deciding that `usize` is really the right type for `Cursor` and not `u64`. I've instead done the conversion here by using `usize::MAX` to make the hash predictably convertible.

Handle message marks on non-64-bit platforms

---

docs/iamb.1
src/base.rs
src/commands.rs
src/main.rs
src/windows/mod.rs

This adds a `:unreads` command that opens a list of unread messages, and `:unreads clear` subcommand that marks all unread rooms as reads.

Add commands for viewing and clearing unreads

---

Cargo.lock
Cargo.toml
README.md

This release includes the following changes:
- #92
- #239
- #240
- #241
- #245
- #253
- #254
- #257
- #269
- #272
- #273
- #274
- #275
- #277
- #278
- #279
- #280
- #281
- #283
- #286
- #301
- #303
- #305
- #314
- #315
- #317
- #319
- #320
- #321
- #322
- #323
- #324
- #325
- #326
- #327
- #328
- #329
- #332

Release v0.0.10

---

docs/iamb.metainfo.xml

I was told not to use remote icons with FlatHub, and the `stock` icons don't seem to play nicely with `appstream-compose`, so I'm just going to remove it. The icon is already included in the `iamb.desktop` file so it should hopefully get picked up from that.

Do not use icons in MetaInfo

---

docs/iamb.5
src/config.rs
src/notifications.rs
src/tests.rs

Fixes #340, as I mention there I have a usecase for using both kinds of notifications at the same time.

Support enabling multiple notification sinks

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
README.md
flake.lock
src/message/mod.rs
src/notifications.rs
src/preview.rs
src/windows/room/chat.rs
src/windows/room/mod.rs
src/worker.rs

This accommodates recent protocol changes and addresses #378.

Bump matrix-sdk dependency to 0.8

---

flake.nix

The original flake.nix did not work to build the latest commit with. This one does, at least in my local tests. I've only tested on an MBP M1, and I don't have any other system with nix (yet), so please test if anyone have other platforms.

Updated rust version and added sqlite in flake.nix

---

.github/workflows/ci.yml

This pulls in the latest `sccache-action` version in order to fix the broken CI.

Update to `mozilla-actions/sccache-action@v0.0.9`

---

docs/iamb.5
src/base.rs
src/config.rs
src/windows/mod.rs

Adds a new order to the settings.sort configuration which puts invites before other rooms. This should counter missing out on invites when the order is set to e.g. "recent".
Note: I did not change any defaults, but would favor `["invites", "favorite", "lowpriority", "unread", "name"]` as default since a user hasn't had a chance to "favorite" or "lowpriority" a new room.

Support an `"invite"` field in the room sorting settings

---

docs/iamb.1
src/base.rs
src/commands.rs
src/main.rs
src/windows/mod.rs
src/windows/room/mod.rs
src/windows/room/space.rs

fixes #49 
Implements commands:
- `:room id show` to show the id of the current room
- `:space child set [++order=<order>] [++suggested] <room-id>` to add the room specified by the id to the currently focused space
- arguments `order` and `suggested` set/update the parameters according to [spec](https://spec.matrix.org/latest/client-server-api/#mspacechild)
- `:space child remove` to remove the selected room from the focused space
- includes a workaround for element-hq/element-web#29606

Support adding rooms to spaces

---

src/message/mod.rs
src/windows/room/scrollback.rs

Hi,
This PR is a fix for #362
The root cause was that the image protocol from a reply header was being ignored.
An image in a reply header is now handled in the same way as an image in the body of the message, with the image position offsets modified to account for the difference in formatting (vertical lines, indent, etc).
It was necessary to break out `Message::show_msg` from `MessageFormatter::push_in_reply` due to the lifetime of the image protocol. 
`Message::show_with_preview` now returns the image protocols of both the body and the reply header. `Scrollback::render` was updated to handle this.

Fix image preview in replies and threads

---

Cargo.lock
Cargo.toml
src/config.rs
src/windows/room/chat.rs
src/windows/room/mod.rs
src/worker.rs

There is a warning that popped up during this change and I have no idea how to deal with it.
```
warning: elided lifetime has a name
--> src/message/mod.rs:964:29
|
957 |     pub fn show_with_preview<'a>(
|                              -- lifetime `'a` declared here
...
964 |     ) -> (Text<'a>, Option<(&dyn Protocol, u16, u16)>) {
|                             ^ this elided lifetime gets resolved as `'a`
|
= note: `#[warn(elided_named_lifetimes)]` on by default
```
Otherwise, this seems to be running fine

Bump matrix-sdk dependency to 0.10.0

---

.github/workflows/ci.yml
Cargo.toml
README.md
rust-toolchain.toml

As of #397, building `iamb` now requires at least Rust 1.83 to build. This PR updates CI and adds a `rust-toolchain.toml` to help people using `cargo` with `rustup` to automatically pull down newer Rust versions.

Bump minimum supported Rust version to 1.83

---

Cargo.lock
Cargo.toml
src/base.rs
src/message/mod.rs
src/windows/room/scrollback.rs

This updates to `modalkit@0.0.21`, `modalkit-ratatui@0.0.21`, and `ratatui-image@5.0.0` (but pointing at a Git SHA that includes benjajaja/ratatui-image#91 for now).

Update to latest `modalkit`, `modalkit-ratatui` and `ratatui-image`

---

src/notifications.rs

For direct messages the room name and the name of the only other participant are usually identical. Only showing one can significantly reduce the clutter in notifications for users with long display names.

Omit room name on desktop notifications for DMs

---

Cargo.lock
Cargo.toml
src/worker.rs

This updates `ratatui-image` to v8.0.1 in order to pull in benjajaja/ratatui-image#97, which fixes an issue someone noticed in `#iamb-users` with resizing images when using halfblocks noticed.

Update to `ratatui-image@8.0.1`

---

Cargo.lock

Updates transitive dependencies in the lockfile. I'll go through the `Cargo.toml` later and find ones that can be updated while keeping the MSRV.

Update lockfile dependencies

---

src/base.rs
src/message/html.rs
src/message/mod.rs
src/message/printer.rs
src/message/state.rs
src/windows/room/chat.rs
src/worker.rs

This takes care of holding on to state events and rendering them in the room timeline. This can be a little annoying in some rooms where there's little room conversation but many join/leaves, but that's already true for other clients too.
Once ulyssa/modalkit#123 is implemented then it should be possible to allow collapsing/expanding multiple sequential events into folds.

Show state events in the timeline

---

src/base.rs
src/commands.rs
src/windows/room/chat.rs
src/windows/room/scrollback.rs

This PR adds support for automatically switching focus to the message bar when entering Insert mode in a room, and also allows using `k`/`<Up>` to move up from the message bar into the message scrollback.
Opening as draft for now because I would like to add tests and maybe also revisit some of the scrolling behaviour.

Support automatically toggling room focus

---

Cargo.lock
Cargo.toml
src/base.rs
src/config.rs
src/windows/mod.rs
src/windows/room/space.rs

This uses the `feruca` crate to help collate room names so that folks can get something better than the byte comparisons that Rust does by default.
I've also updated profiles to be deserialized into a `BTreeMap` so that they'll be consistently printed in the same order in the list added in #432.

Do proper Unicode collation on room names

---

src/base.rs
src/config.rs
src/main.rs
src/message/mod.rs
src/tests.rs
src/windows/room/scrollback.rs
src/worker.rs

This saves read receipts per message thread and fixes the remaining issues from #292.
remaining issues to be fixed in later PRs:
- unread messages in threads are not marked as "Unread" in the room list
- previously when the last message in the room was in the thread the room was always unread
- there is way to discover which thread in the room is unread
- should be implemented with a `:threads` overview
- users that have both an unthreaded receipt and a receipt for the main thread are shown twice in the receipt gutter
- this is only an issue if some users in the room use clients that only implement unthreaded receipts like old versions of iamb
- `load_older_one` only loads receipts for the main thread
includes #435

Implement receipts per thread

---

src/message/html.rs
src/message/state.rs

While browsing through a room, I realized that display name changes should get highlighting in the same way that user IDs are for join/leave events.

Apply user highlighting to display name changes

---

docs/iamb.5
src/config.rs
src/message/html.rs
src/message/printer.rs
src/tests.rs

see `#iamb-users` for context
This converts tabs to spaces according to the new config option `tabstop`.

Fix display of tabs in code blocks

---

src/base.rs
src/windows/room/scrollback.rs

When selecting an older line in scrollback, the last line of the newest message is replaced by "Use G to jump to latest message". This is annoying since the newest message is oftentimes the most relevant one.
This PR adds a blank line even if typing notices are disabled to prevent this from happening.

Make scrollback display stable with `typing_notice_display = false`

---

src/message/html.rs

According to the [spec](https://spec.matrix.org/v1.14/client-server-api/#mroommessage-msgtypes), the html `<s>` tag should be supported.
Maybe we also want to remove `<strike>` since it is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/strike) and the matrix spec doesn't suggest it.

Add missing `<s>` tag in HTML parsing

---

src/message/mod.rs

Show image alt text in the middle of the area to make it more visible when the image is partially off-screen on the top.
Also the text "Loading..." doesn't describe the image not fitting in the visible space for the message and "Cut off..." is a bit more descriptive while not being longer.

Improve image preview placeholder

---

Cargo.lock
Cargo.toml
src/base.rs
src/main.rs
src/windows/room/chat.rs
src/windows/room/scrollback.rs

This pulls in the latest changes to `modalkit` and `modalkit-ratatui`, and updates how its used in `iamb` to account for changes in the crates.

Update to modalkit{,-ratatui}@0.0.23

---

src/main.rs

This makes the border of unfocused windows dim so the focused window stands out.
fixes #147

Highlight border of focused window

---

Cargo.lock
Cargo.toml
src/message/html.rs
src/message/mod.rs
src/windows/room/chat.rs

This PR introduces the `linkify` dependency to gather links if no `"formated_body"` exits. Links are available in `:open` but are not visually changed. It only works for links that include the protocol but I believe this limitation comes from the `url` crate.
fixes #370

Recognise URLs in plain text message bodies

---

src/config.rs

This update enhances config directory resolution on macOS by prioritizing the `XDG_CONFIG_HOME` environment variable when it is set (e.g., for nix-home users with `xdg.enable = true`). If `XDG_CONFIG_HOME` is not defined, the fallback remains the default path: `~/Library/Application Support`.
This change improves compatibility with XDG-based configurations on macOS, providing a more consistent experience across different environments.

Support `XDG_CONFIG_HOME` on macOS for config directory resolution

---

src/message/html.rs

Before, quotes are just rendered as an indentation. This adds a gray vertical bar
> like this.
The PR doesn't change the text color because it is not needed to recognize a quote imo.

Make blockquotes in message visually distict

---

src/base.rs
src/main.rs
src/notifications.rs
src/worker.rs

Currently desktop notifications are never dismissed. When a user has a notification daemon that keeps all notifications until they are explicitly closed, they have to manually dismiss the notification to have an empty feed.
This adds logic to close the notification when a read receipt is sent. This matches the behavior of other clients like element-desktop.

Clear desktop notification when message is read

---

Cargo.lock
Cargo.toml

This updates the `modalkit` and `modalkit-ratatui` dependencies to v0.0.24, which pulls in the fix for #477 and the behaviour of `cc`.

Update to modalkit{,-ratatui}@0.0.24

---

src/config.rs
src/notifications.rs
src/tests.rs

This patch adds a configuration element called `play_sound` (bool, false by default) that when set true, 
it will tell the notification to use sound hint called `message-new-instant` which then plays a sound, 
depending on the platform the app is running in.
(I haven't really used Rust before so bear with me :sweat_smile: )

Add config option for playing sound-hints with desktop notifications

---

flake.lock
flake.nix

Currently pulls in rust 1.83, which is too old to build iamb now.
I'm going to try to keep the nix stuff up to date from now on.

Update Nix flake and its lockfile

---

src/config.rs
src/message/mod.rs
src/windows/mod.rs
src/windows/room/chat.rs
src/windows/room/mod.rs

run `cargo clippy --fix` to resolve warnings introduced in #500
The only remaining warnings are about enum size differences in `RoomState` and `IambWindow`. Both are because `RoomState::Chat` is too large. I'm not sure whether to wrap this in a `Box` or to add a `#[allow(clippy::large_enum_variant)]`.

Fix most clippy warnigs
